name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: stable
          components: clippy, rustfmt

    - name: Install cargo lambda
      run: cargo install --locked cargo-lambda

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run cargo check
      run: cargo check --all-features --locked --release

    - name: Run cargo build
      run: cargo build --locked --release

    - name: Run cargo lambda build
      run: cargo lambda build --locked --release
